

export const products = [

    {
        productId: 1,
        title: "Nike Black",
        subtitle: "Elegant Sportsy Shoes",
        unit_price: 100,
        secondUnit: "",
        stock: 4,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        color: "grey",
        size: 40,
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_32_yfkmr5.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_46_k1twnd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_50_tjh2fy.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_39_lmhguz.png",
            null
        ],
        discount: 5,
        discountPrice: 95,
    }, 
    {
        productId: 1,
        title: "Nike Black",
        subtitle: "Elegant Sportsy Shoes",
        unit_price: 100,
        secondUnit: "",
        stock: 14,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        color: "grey",
        size: 41,
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_32_yfkmr5.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_46_k1twnd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_50_tjh2fy.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_39_lmhguz.png",
            null
        ],
        discount: 5,
        discountPrice: 95,
    },
    {
        productId: 1,
        title: "Nike Black",
        subtitle: "Elegant Sportsy Shoes",
        unit_price: 100,
        secondUnit: "",
        stock: 9,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        color: "grey",
        size: 42,
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_32_yfkmr5.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_46_k1twnd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_50_tjh2fy.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690916618/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_39_lmhguz.png",
            null
        ],
        discount: 5,
        discountPrice: 95,
    },
  
    {
        productId: 100,
        title: "Easy Care",
        subtitle: "Comfortable Elastic Pants",
        unit_price: 60,
        secondUnit: "",
        stock: 3,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        color: "sky",
        size: "xs",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_25_jkdthp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_35_kj8vk7.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_17_lcesyr.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_11_vtk80d.png",
            null
        ],
        discount: 10,
        discountPrice: 54,
    },
    {
        productId: 100,
        title: "Easy Care",
        subtitle: "Comfortable Elastic Pants",
        unit_price: 60,
        secondUnit: "",
        stock: 13,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        color: "sky",
        size: "s",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_25_jkdthp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_35_kj8vk7.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_17_lcesyr.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_11_vtk80d.png",
            null
        ],
        discount: 10,
        discountPrice: 54,
    },
    {
        productId: 100,
        title: "Easy Care",
        subtitle: "Comfortable Elastic Pants",
        unit_price: 60,
        secondUnit: "",
        stock: 3,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        color: "sky",
        size: "l",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_25_jkdthp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_35_kj8vk7.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920657/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_17_lcesyr.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690920656/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_11_vtk80d.png",
            null
        ],
        discount: 10,
        discountPrice: 54,
    },
    {
        productId: 200,
        title: "Easy Care",
        subtitle: "Brown Cool Shirt for Men",
        unit_price: 90,
        secondUnit: "",
        stock: 10,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        color:"brown",
        size:"s",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928472/web%20access/samples%20for%20e-commerce/Shirts/1-a_4_agvwve.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928471/web%20access/samples%20for%20e-commerce/Shirts/1-a_3_blrhlj.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_2_ucivkz.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_1_mlmg8l.png",
            null
        ],
        discount: 10,
        discountPrice: 81,
    },
    {
        productId: 200,
        title: "Easy Care",
        subtitle: "Brown Cool Shirt for Men",
        unit_price: 90,
        secondUnit: "",
        stock: 12,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        color:"brown",
        size:"m",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928472/web%20access/samples%20for%20e-commerce/Shirts/1-a_4_agvwve.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928471/web%20access/samples%20for%20e-commerce/Shirts/1-a_3_blrhlj.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_2_ucivkz.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_1_mlmg8l.png",
            null
        ],
        discount: 10,
        discountPrice: 81,
    },
    {
        productId: 200,
        title: "Easy Care",
        subtitle: "Brown Cool Shirt for Men",
        unit_price: 90,
        secondUnit: "",
        stock: 20,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        color:"brown",
        size:"xxl",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928472/web%20access/samples%20for%20e-commerce/Shirts/1-a_4_agvwve.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928471/web%20access/samples%20for%20e-commerce/Shirts/1-a_3_blrhlj.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_2_ucivkz.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1690928470/web%20access/samples%20for%20e-commerce/Shirts/1-a_1_mlmg8l.png",
            null
        ],
        discount: 10,
        discountPrice: 81,
    },
    {
        productId: 300,
        title: "Hoodie Fach",
        subtitle: "White Cool Hoodie for Men",
        unit_price: 120,
        secondUnit: "",
        stock: 10,
        description: "Introducing our 'Signature Series' hoodie. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "hoodies",
        color:"white",
        size:"s",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/zfr8snocnkjh6pm38ufd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/jam1f296cwos2etipzml.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/fc1fomkm9q9ydv7qexjp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/rc991806twl6mekx2ndb.png",
            null
        ],
        discount: 20,
        discountPrice: 96,
    },
    {
        productId: 300,
        title: "Hoodie Fach",
        subtitle: "White Cool Hoodie for Men",
        unit_price: 120,
        secondUnit: "",
        stock: 12,
        description: "Introducing our 'Signature Series' hoodie. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "hoodies",
        color:"white",
        size:"xs",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/zfr8snocnkjh6pm38ufd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/jam1f296cwos2etipzml.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/fc1fomkm9q9ydv7qexjp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/rc991806twl6mekx2ndb.png",
            null
        ],
        discount: 20,
        discountPrice: 96,
    },
    {
        productId: 300,
        title: "Hoodie Fach",
        subtitle: "White Cool Hoodie for Men",
        unit_price: 120,
        secondUnit: "",
        stock: 20,
        description: "Introducing our 'Signature Series' hoodie. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "hoodies",
        color:"white",
        size:"l",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/zfr8snocnkjh6pm38ufd.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/jam1f296cwos2etipzml.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/fc1fomkm9q9ydv7qexjp.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464671/web%20access/samples%20for%20e-commerce/Hoodies/rc991806twl6mekx2ndb.png",
            null
        ],
        discount: 20,
        discountPrice: 96,
    },
    {
        productId: 400,
        title: "Mochi Bag",
        subtitle: "Black Cool bag",
        unit_price: 110,
        secondUnit: "",
        stock: 10,
        description: "Introducing our 'Signature Series' bag. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "bags",
        color:"black",
        size:"s",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464700/web%20access/samples%20for%20e-commerce/Bags/aijhns1q4clrpis2ntph.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/sl0xrrqnxdspv5othgmg.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/tcunbufqseoudnup8d6b.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/jvkivbds4kn8xqf9vnc7.png",
            null
        ],
        discount: 10,
        discountPrice: 99,
    },
    {
        productId: 400,
        title: "Mochi Bag",
        subtitle: "Black Cool bag",
        unit_price: 110,
        secondUnit: "",
        stock: 12,
        description: "Introducing our 'Signature Series' bag. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "bags",
        color:"black",
        size:"xs",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464700/web%20access/samples%20for%20e-commerce/Bags/aijhns1q4clrpis2ntph.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/sl0xrrqnxdspv5othgmg.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/tcunbufqseoudnup8d6b.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/jvkivbds4kn8xqf9vnc7.png",
            null
        ],
        discount: 10,
        discountPrice: 99,
    },
    {
        productId: 400,
        title: "Mochi Bag",
        subtitle: "Black Cool bag",
        unit_price: 110,
        secondUnit: "",
        stock: 15,
        description: "Introducing our 'Signature Series' bag. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "bags",
        color:"black",
        size:"m",
        img: [
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464700/web%20access/samples%20for%20e-commerce/Bags/aijhns1q4clrpis2ntph.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/sl0xrrqnxdspv5othgmg.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/tcunbufqseoudnup8d6b.png",
            "https://res.cloudinary.com/derdim3m6/image/upload/v1704464701/web%20access/samples%20for%20e-commerce/Bags/jvkivbds4kn8xqf9vnc7.png",
            null
        ],
        discount: 10,
        discountPrice: 99,
    },
]
